name: Deploy Web App

on:
  push:
    branches: [ main ]  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload site to GitHub Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
