name: Lint & Build Android App

on:
  push:
    paths:
      - 'mobile-android-app/**'

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: mobile-android-app

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Lint
        run: ./gradlew lint

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: bingepal-debug-apk
          path: mobile-android-app/app/build/outputs/apk/debug/app-debug.apk
